CREATE TABLE `prefix_referenzen` (
  `referenzen_screen` varchar(100) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL DEFAULT '',
  `referenzen_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `referenzen_title` varchar(100) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL DEFAULT '',
  `user_id` int(11) NOT NULL DEFAULT '0',
  `referenzen_time` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `referenzen_recht` int(11) NOT NULL DEFAULT '0',
  `referenzen_kat` varchar(100) COLLATE latin1_german1_ci DEFAULT NULL,
  `referenzen_text` text CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL,
  `referenzen_designer` varchar(100) CHARACTER SET latin1 COLLATE latin1_general_ci NOT NULL DEFAULT '',
  `referenzen_slicer` varchar(100) COLLATE latin1_german1_ci DEFAULT NULL,
  `referenzen_anpasser` varchar(100) COLLATE latin1_german1_ci DEFAULT NULL,
  `referenzen_code` varchar(100) COLLATE latin1_german1_ci DEFAULT NULL,
  `referenzen_preis` varchar(100) COLLATE latin1_german1_ci DEFAULT NULL,
  `referenzen_anmerkung` varchar(100) COLLATE latin1_german1_ci DEFAULT NULL,
  `referenzen_vprogramme` varchar(100) COLLATE latin1_german1_ci DEFAULT NULL,
  `referenzen_zeit` varchar(100) COLLATE latin1_german1_ci DEFAULT NULL,
  `referenzen_release` varchar(100) COLLATE latin1_german1_ci DEFAULT NULL,
  `referenzen_name` varchar(100) COLLATE latin1_german1_ci DEFAULT NULL,
  `referenzen_nname` varchar(100) COLLATE latin1_german1_ci DEFAULT NULL,
  `referenzen_email` varchar(100) COLLATE latin1_german1_ci DEFAULT NULL,
  `referenzen_icq` varchar(100) COLLATE latin1_german1_ci DEFAULT NULL,
  `referenzen_hp` varchar(100) COLLATE latin1_german1_ci DEFAULT NULL,
  `referenzen_forum` varchar(200) COLLATE latin1_german1_ci NOT NULL,
  PRIMARY KEY (`referenzen_id`)
) ENGINE=MyISAM AUTO_INCREMENT=14 DEFAULT CHARSET=latin1 COLLATE=latin1_german1_ci COMMENT='powered by JayDee'